# Description:  
#
# Author: Harshvardhan Karn
###############################################################################################
#Steps:
#
###############################################################################################

---
- hosts: localhost
  tasks:
    - name: chmod
      shell: chmod +x create-aks.sh
      
    - name: Create Azure cluster
      shell: |
        export NODE_COUNT=3                                                                                                                                                                                            
        export NODE_VM_SIZE=Standard_D2                                                                                                                                                                                
        export USERNAME={azure_user}                                                                                                                                                               
        export PASSWORD={azure_password}
        ./create-aks.sh
