# Description:  
# Author: Harshvardhan Karn
###############################################################################################
#Steps:
#
###############################################################################################

---
- hosts: localhost
  tasks:
    - name: chmod
      shell: chmod +x delete-aks.sh

    - name: Delete Azure cluster
      shell: |
        export NODE_COUNT=3                                                                                                                                                                                            
        export NODE_VM_SIZE=Standard_D2                                                                                                                                                                                
        export USERNAME={azure_user}                                                                                                                                                               
        export PASSWORD={azure_password}
        ./delete-aks.sh